

Epoch 0, train loss: 0.00000 train f error: 0.00005; data l2 error: 1.94944:   0%|▎                                                                                                                                                 | 1/500 [00:47<6:35:39, 47.57s/it]










Epoch 10, train loss: 0.00000 train f error: 0.00005; data l2 error: 1.94944:   2%|███▏                                                                                                                                            | 11/500 [08:46<6:29:45, 47.82s/it]
Traceback (most recent call last):
  File "/home/kamyara/PINO/PINO/train_burgers.py", line 87, in <module>
    run(args, config)
  File "/home/kamyara/PINO/PINO/train_burgers.py", line 39, in run
    train_2d_burger(model,
  File "/home/kamyara/PINO/PINO/train_utils/train_2d.py", line 172, in train_2d_burger
    loss_u, loss_f = PINO_loss(pde_out, pde_x[:, 0, :, 0])
  File "/home/kamyara/PINO/PINO/train_utils/losses.py", line 235, in PINO_loss
    loss_u = F.mse_loss(boundary_u, u0)
  File "/home/kamyara/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/functional.py", line 3252, in mse_loss
    def mse_loss(
KeyboardInterrupt