  0%|                                                                                                                                                                                                                                         | 0/500 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/kamyara/PINO/PINO/train_burgers.py", line 87, in <module>
    run(args, config)
  File "/home/kamyara/PINO/PINO/train_burgers.py", line 39, in run
    train_2d_burger(model,
  File "/home/kamyara/PINO/PINO/train_utils/train_2d.py", line 165, in train_2d_burger
    out = model(x,padding)#.reshape(y.shape)
  File "/home/kamyara/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kamyara/PINO/PINO/models/fourier2d.py", line 74, in forward
    x = self.activation(x)
RuntimeError: CUDA out of memory. Tried to allocate 208.00 MiB (GPU 0; 1.93 GiB total capacity; 662.05 MiB already allocated; 187.31 MiB free; 690.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF